# **Python für Ingenieure** ??        ### Wichtig###
<!-- Lizensiert unter (CC BY 2.0) Gert Herold, 2019 -->
***************
# 6. NumPy

>NumPy is the fundamental package for scientific computing with Python. It contains among other things:
>  *  a powerful N-dimensional array object
>  *  sophisticated (broadcasting) functions
>  *  tools for integrating C/C++ and Fortran code
>  *  useful linear algebra, Fourier transform, and random number capabilities
>
> &mdash; <cite>[NumPy.org](https://numpy.org/), 2019</cite>


Das Python-Modul NumPy beinhaltet (mit seinen Untermodulen) eine mächtige Toolbox, die den Umgang mit Daten unter Python sehr komfortabel macht.
*****************
>NumPy is the fundamental package for scientific computing with Python. It contains among other things:
> * a powerful N-dimensional array object
> * sophisticated (broadcasting) functions
> * tools for integrating C/C++ and Fortran code
> * useful linear algebra, Fourier transform, and random number capabilities
>
**************************
> NumPy هي الحزمة الأساسية للحوسبة العلمية باستخدام Python. يحتوي من بين أشياء أخرى:
> * كائن صفيف قوي الأبعاد N
> * وظائف متطورة (إذاعية)
> * أدوات لدمج كود C / C ++ و Fortran
> * إمكانيات الجبر الخطي وتحويل فورييه والأرقام العشوائية المفيدة
******************

## 6.1. Arrays

Das wohl wichtigste Werkzeug, das NumPy mit sich bringt, ist der Datentyp [*ndarray*](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html), mit dem sich beliebig-dimensionale Vektoren/Matrizen/Tensoren (kurz: Arrays) verwirklichen lassen.

### 6.1.1. Arrays anlegen

Eine einfache Möglichkeit, ein Array zu erzeugen, ist mithilfe der [*array()*](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)-Funktion:

*********************************

## 6.1. Arrays

Probably the most important tool that NumPy comes with is the data type [* ndarray *](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html), with which any- let dimensional vectors / matrices / tensors (short: arrays) be realized.
*****


### 6.1.1. Create arrays

An easy way to create an array is by using the [* array () *](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html) function:

In [2]:
from numpy import array, newaxis

a = array([1, 2, 3, 6 ,8])
print(a)
print(type(a))
print(a.dtype)
print(a[2])


[1 2 3 6 8]
<class 'numpy.ndarray'>
int32
3


Im Unterschied zu einer Python-Liste sind Elemente eines Arrays für gewöhnlich numerisch sowie stets vom gleichen Typ. 
Eine Auflistung von möglichen Array-Datentypen findet sich in der [Numpy-Dokumentation](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).
Befinden sich in einer als Array zu speichernden Liste Variablen unterschiedlichen Typs, wird, wenn möglich, ein Datentyp festgelegt, mit dem alle Werte abgebildet werden können.
******
Unlike a Python list, elements of an array are usually numeric and always of the same type.
A list of possible array data types can be found in the [Numpy documentation](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).
If there are variables of different types in a list to be saved as an array, a data type is defined, if possible, with which all values can be mapped.

In [3]:
###Wichtig####
from numpy import array, newaxis


liste_a = [1,   7, -3,  5, 12]
liste_b = [2, 7.5, 11, -1,  0]

a = array(liste_a)
b = array(liste_b)

print(f'Liste: {liste_a}\nArray: {a}\n{a.dtype}\n')               
print(f'Liste: {liste_b}\nArray: {b}\n{b.dtype}\n')



Liste: [1, 7, -3, 5, 12]
Array: [ 1  7 -3  5 12]
int32

Liste: [2, 7.5, 11, -1, 0]
Array: [ 2.   7.5 11.  -1.   0. ]
float64



In [4]:
from numpy import array, newaxis

list_1=[1,2,3,4,5,6,7,8]              #  example
a=array(list_1)
print(a,a.dtype,type(a),a.shape,a.ndim)

[1 2 3 4 5 6 7 8] int32 <class 'numpy.ndarray'> (8,) 1


In [6]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) #3x3 -> 2d-array
B = np.array([[9,8,7],[6,5,4],[3,2,1]])
C = np.array([A,B])
print([A,A.shape,A.ndim])
print('**********************\n')

print(A,A.shape,A.ndim)
print('**********************\n')

print([(i,i.shape ,i.ndim) for i in [A,B,C]])


print('**********************\n')
print(C)
print('**********************\n')
print([i.shape for i in [A,B,C]])
print('**********************\n')

F = np.array([([1,2,3],[4,5,6],[7,8,9])])
print('F=',F,F.ndim)


print('**********************\n')
D=np.array([[1,2],
             [3,4],
             [5,6]])
[D]

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), (3, 3), 2]
**********************

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 2
**********************

[(array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), (3, 3), 2), (array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]]), (3, 3), 2), (array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]]), (2, 3, 3), 3)]
**********************

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]]
**********************

[(3, 3), (3, 3), (2, 3, 3)]
**********************

F= [[[1 2 3]
  [4 5 6]
  [7 8 9]]] 3
**********************



[array([[1, 2],
        [3, 4],
        [5, 6]])]

In [14]:
a = np.arange(10) # 0 .. n-1  (!)
print(a)

b = np.arange(1, 9, 2) # start, end (exclusive), step
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


Mehrdimensionale Arrays lassen sich einfach über Unterlisten erzeugen:
*****************************
Multi-dimensional arrays can be easily generated using sublists:

In [15]:
import numpy as np

A=np.array([1,2])
print(A.shape,A.ndim)
D=A[newaxis]
print('D=',D,D.ndim)
R=D[newaxis]
print('R=',R,R.ndim)

(2,) 1
D= [[1 2]] 2
R= [[[1 2]]] 3


In [45]:
c = array([[1],[3],[2]])
print('array:\n',c)
print('dimension:',c.ndim)        ## ?
print('shape:',c.shape)
print('size:',c.size)

#toll
c

array:
 [[1]
 [3]
 [2]]
dimension: 2
shape: (3, 1)
size: 3


array([[1],
       [3],
       [2]])

In [46]:
c = array([1,3,2])
print('array:\n',c)
print('dimension:',c.ndim)        ## ?
print('shape:',c.shape)
print('size:',c.size)

#toll
c

array:
 [1 3 2]
dimension: 1
shape: (3,)
size: 3


array([1, 3, 2])

In [66]:
c = array([[1,2,1],[3,4,4],[6,7,8]])
print('array:\n',c)
print('dimension:',c.ndim)        ## ?
print('shape:',c.shape)
print('size:',c.size)

#toll
print(c)
print('*********************')



array:
 [[1 2 1]
 [3 4 4]
 [6 7 8]]
dimension: 2
shape: (3, 3)
size: 9
[[1 2 1]
 [3 4 4]
 [6 7 8]]
*********************


In [23]:
print(np.ones((3,3)))
print(np.ones(5))
print(np.zeros(5))
print(np.ones((3,3,5)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


### 6.1.2. Indizierung von Arrays

Der Abruf von Elementen eines Arrays (*Slicing*) funktioniert ähnlich wie bei einer Liste bzw. die Möglichkeiten, eine Liste zu indizieren, funktionieren auch hier:
***********************************
### 6.1.2. Indexing arrays           ###wichtig

The retrieval of elements of an array (* slicing *) works in a similar way to a list 
or the possibilities to index a list also work here:
***************************
يعمل استرجاع عناصر المصفوفة (* slicing *) بطريقة مشابهة للقائمة
أو إمكانيات فهرسة قائمة تعمل أيضًا هنا:

In [67]:
###wichtig###
#*****************************
from numpy import array
liste_d = [[  1,  1,  3,  4,  5],
           [  1,  1,  8,  9, 10],
           [  1,  1, 13, 14, 15],
           [  1,  1, 18, 19, 20]]

####??B      (3d array):      7 x 1 x 5
d = array(liste_d)

print(liste_d[2][3])
print(liste_d[3][3])
print(d[2][3])
print(d)
print('d[2]=',d[2])
print('**********************')
print(d[0])
print('d[0][::-1]=',d[0][::-1])
print(d[0][1::-1])
print(d[0][3:2:-1])   ##??

print('aaaaaaaaa',d[0][3::-1])
print('aaaaaaaaa',d[0][3::-2])
print('aaaaaaaaa',d[0][3:0:-2])
print('aaaaaaaaa',d[0][3:0:-1])
print('aaaaaaaaa',d[0][2::1])
print('aaaaaaaaa',d[0][:3:1])
print('aaaaaaaaa',d[0][0:3:1])    # in the postive step increament execution he excludes the second index Argument
#which  interpritted as the End parameter
 # in the negative step increament execution he excludes the first index Argument
#which  interpritted as the End parameter 

14
19
14
[[ 1  1  3  4  5]
 [ 1  1  8  9 10]
 [ 1  1 13 14 15]
 [ 1  1 18 19 20]]
d[2]= [ 1  1 13 14 15]
**********************
[1 1 3 4 5]
d[0][::-1]= [5 4 3 1 1]
[1 1]
[4]
aaaaaaaaa [4 3 1 1]
aaaaaaaaa [4 1]
aaaaaaaaa [4 1]
aaaaaaaaa [4 3 1]
aaaaaaaaa [3 4 5]
aaaaaaaaa [1 1 3]
aaaaaaaaa [1 1 3]


Darüber hinaus ist können die Indizierungen hier einfach per Komma abgetrennt (also als Tupel angegeben) werden:
**********************
In addition, the indexes can be separated here simply by a comma (i.e. specified as a tuple):

In [34]:
d[2,3]

14

Das erlaubt auch ein einfaches Abrufen von Sub-Arrays:
**************************
This also allows easy retrieval of sub-arrays:

In [35]:
#e = d[:2] ##?


e = d[:2,3:]   ##?
e

array([[ 4,  5],
       [ 9, 10]])

Diese Index-Operationen sind rechentechnisch sehr effizient, da hierdurch keine neuen Daten im Speicher hinterlegt werden, sondern die Einträge des neuen Arrays lediglich auf die bereits angelegten Daten zeigen.
Das hat zur Folge, dass Änderungen im neuen Array auch im ursprünglichen Array auftauchen:
******************************
These index operations are computationally very efficient, since they do not store any new data in the memory, but rather the entries in the new array only point to the data that has already been created.
As a result, changes in the new array also appear in the original array:
*******************************
عمليات الفهرسة هذه فعالة جدًا من الناحية الحسابية ، نظرًا لأنها لا تخزن أي بيانات جديدة في الذاكرة ، بل تشير الإدخالات في الصفيف الجديد فقط إلى البيانات التي تم إنشاؤها بالفعل.
ونتيجة لذلك ، تظهر التغييرات في الصفيف الجديد أيضًا في الصفيف الأصلي:

In [38]:
##wichtig###
    

e[0,1] = 12345    ##?
e

array([[    4, 12345],
       [    9,    10]])

###Wichtig### 

Hilfreich ist auch die Möglichkeit, Integer-Arrays selbst zur Indizierung zu verwenden:
****************
The option of using integer arrays for indexing is also helpful:

In [54]:
#B      (3d array):      7 x 1 x 5
index = array([0,2,3])  
print(index)
print('***********')
print (d[:])
print('***********')
print (d[:,index])
print('***********')
print (d[:,(2,4)])
print('***********')
print (d[:,2])
print('***********')

[0 2 3]
***********
[[    1     1     3     4 12345]
 [    1     1     8     9    10]
 [    1     1    13    14    15]
 [    1     1    18    19    20]]
***********
[[ 1  3  4]
 [ 1  8  9]
 [ 1 13 14]
 [ 1 18 19]]
***********
[[    3 12345]
 [    8    10]
 [   13    15]
 [   18    20]]
***********
[ 3  8 13 18]
***********


Es können auch Arrays mit Bool'schen Ausdrücken verwendet werden. Mit `False` können so Werte, die nicht gewünscht sind, maskiert werden:
*********************
Arrays with Boolean expressions can also be used. With `False`, values that are not desired can be masked:
****************************
يمكن أيضًا استخدام المصفوفات ذات التعبيرات المنطقية. باستخدام "False" ، يمكن إخفاء القيم غير المرغوبة:

In [57]:
b_ind = array([False, True, True, True])
b, b[b_ind]

(array([1, 3, 5, 7]), array([3, 5, 7]))

Bei Indizierung mit Integer- oder Boolean-Arrays werden Kopien der Daten angelegt. Für die meisten praktischen Anwendungen spielt es keine Rolle, ob die Daten kopiert oder ob nur Speicheradressen umgeleitet werden.
Bei der Fehlersuche in Programmen sollte man sich dessen jedoch bewusst sein.
***
When indexing with integer or Boolean arrays, copies of the data are created. For most practical applications, it does not matter whether the data is copied or whether only memory addresses are redirected.
However, you should be aware of this when troubleshooting programs.

 ### wichtig ###
 *********************
 
### 6.1.3. Rechnen mit Arrays und Broadcasting   

**Beispiel 1:** Es sollen die Elemente einer Liste mit den entsprechenden Elementen einer anderen Liste addiert werden. Dies ist z.B. möglich über eine Schleife:

************
### 6.1.3. Computing with arrays and broadcasting

** Example 1: ** The elements of a list should be added with the corresponding elements of another list. This is e.g. possible via a loop:

In [12]:
neue_liste = []
for i,j in zip(liste_a, liste_b):     ##?? zip
    neue_liste += [i+j]
print(liste_a)
print(liste_b)
print(neue_liste)

#Python's zip() function is defined as zip(*iterables) . The function takes in iterables as arguments and returns an iterator.
#This iterator generates a series of tuples containing elements from each iterable. 
#zip() can accept any type of iterable, such as files, lists, tuples, dictionaries, sets, and so on.

[1, 7, -3, 5, 12]


Etwas übersichtlicher wird das mit einer List Comprehension:
*****
This becomes a little clearer with a list comprehension:
*****
يصبح هذا أكثر وضوحا مع قائمة الفهم:

    ###Wichtig###
#Iterate through two sequences simultaneously: zip

for x,y in zip('Hallo',[12, -7.3, 1, 0, False]):
    print(x,y)

In [14]:
[i+j for i,j in zip(liste_a, liste_b)]

[3, 14.5, 8, 4, 12]

Liegen die Daten als Array vor, geht das noch einfacher:

In [15]:
a+b

array([ 3. , 14.5,  8. ,  4. , 12. ])

**Beispiel 2:** Wir wollen alle Werte einer Liste mit 100 multiplizieren. Auch hier muss diese Multiplikation für jedes Element einzeln vorgenommen werden:

In [16]:
[i*100 for i in liste_b]

[200, 750.0, 1100, -100, 0]

Rechenoperationen mit Arrays hingegen sind sehr effizient gestaltet.
Hier schreibt man einfach:

In [17]:
b*100

array([ 200.,  750., 1100., -100.,    0.])

Das funktioniert mit beliebig-dimensionalen Arrays:

In [18]:
d,d*100

(array([[    1,     1,     3,     4, 12345],
        [    1,     1,     8,     9,    10],
        [    1,     1,    13,    14,    15],
        [    1,     1,    18,    19,    20]]),
 array([[    100,     100,     300,     400, 1234500],
        [    100,     100,     800,     900,    1000],
        [    100,     100,    1300,    1400,    1500],
        [    100,     100,    1800,    1900,    2000]]))

Allgemein erlaubt NumPy die Kombination von zwei Arrays verschiedener Größen, wenn für die jeweils *hinteren Dimensionen* der Arrays eine der folgenden Bedingungen erfüllt ist:
  * die Anzahl der Elemente ist jeweils gleich
  * ein Array hat in dieser Dimension genau einen Eintrag

Im ersten Fall wird jedes Element eines Arrays mit dem entsprechenden Element des zweiten Arrays kombiniert. 
Im zweiten Fall wird das einzelne Element auf alle anderen angewendet.
Unterscheidet sich die Anzahl der Dimensionen (auch: Achsen bzw. engl. *axes*), so werden dem Array mit weniger Dimensionen entsprechend viele Achsen hinzugefügt.

Diese Funktionalitäten werden als [Broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html) bezeichnet.
Das bedeutet z.B. für das 2D-Array `d` mit den Dimensionen (4, 5)
#Broadcasting #https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html
********************
NumPy generally allows the combination of two arrays of different sizes if one of the following conditions is met for the * rear dimensions * of the arrays:
   * the number of elements is the same
   * an array has exactly one entry in this dimension

In the first case, each element of an array is combined with the corresponding element of the second array.
In the second case, the single element is applied to all others.
If the number of dimensions differs (also: axes or * axes *), the number of axes with fewer dimensions is added accordingly.

These functionalities are referred to as [broadcasting] (https://numpy.org/devdocs/user/theory.broadcasting.html).
That means e.g. for the 2D array `d` with dimensions (4, 5)
#Broadcasting #https: //docs.scipy.org/doc/numpy/user/basics.broadcasting.html

In [19]:
d.shape

(4, 5)

dass Operation neben Skalaren z.B. auch mit Arrays mit den Dimensionen 
  * (4, 5)
  * (1, 1)
  * (1, 5)
  * (4, 1)
  * (5, )
  * (3, 4, 5)
  * (75, 1, 5)
  * usw.

möglich sind.

In [20]:
print(a.shape, d.shape,'\n')
print(a,'\n')
print(d,'\n')
print(a+d,'\n')

(5,) (4, 5) 

[ 1  7 -3  5 12] 

[[    1     1     3     4 12345]
 [    1     1     8     9    10]
 [    1     1    13    14    15]
 [    1     1    18    19    20]] 

[[    2     8     0     9 12357]
 [    2     8     5    14    22]
 [    2     8    10    19    27]
 [    2     8    15    24    32]] 



In [21]:
f = array([[10],[20],[30],[40]])
print(f.shape, d.shape,'\n')
print(f,'\n')
print(d,'\n')
print(f*d,'\n')

(4, 1) (4, 5) 

[[10]
 [20]
 [30]
 [40]] 

[[    1     1     3     4 12345]
 [    1     1     8     9    10]
 [    1     1    13    14    15]
 [    1     1    18    19    20]] 

[[    10     10     30     40 123450]
 [    20     20    160    180    200]
 [    30     30    390    420    450]
 [    40     40    720    760    800]] 



Falls die beiden Arrays nicht den obigen Regeln entsprechend kombinierbar sind, wird eine Fehlermeldung ausgegeben:

In [18]:
e+d

ValueError: operands could not be broadcast together with shapes (2,2) (4,5) 

Mitunter ist es aber gewünscht, mit allen Einzeleinträgen eines beliebigen Arrays Operationen auf ein Array anderer Dimension auszuführen. Nehmen wir zum Beispiel die obige Multiplikation des Arrays `d` mit der Zahl 100. Nun wollen wir dieses Array sowohl mit 100 als auch mit 200 multiplizieren:

In [62]:
print(d*100)
print(d*200)

# Geht das auch in einem Schritt?
mult = array([100,200])
print(mult)
print(d * mult)

[[    100     100     300     400 1234500]
 [    100     100     800     900    1000]
 [    100     100    1300    1400    1500]
 [    100     100    1800    1900    2000]]
[[    200     200     600     800 2469000]
 [    200     200    1600    1800    2000]
 [    200     200    2600    2800    3000]
 [    200     200    3600    3800    4000]]
[100 200]


ValueError: operands could not be broadcast together with shapes (4,5) (2,) 

Das ist so nicht möglich, weil entgegen den Broadcastregeln versucht wird, zwei Elemente fünf Elemente zu projizieren.
Das eigentliche Ziel war aber ein ganz anderes, nämlich *alle* Elemente des einen Arrays mit *allen* Elementen des anderen zu multiplizieren.
Hierfür müssen dem 1D-Array weitere Dimensionen/Achsen hinzugefügt werden.
Das geht mit dem Pseudo-Index `newaxis`:

In [63]:
from numpy import newaxis
print(d * mult[:, newaxis, newaxis])
print('\nShapes:', d.shape, (mult[:, newaxis, newaxis]).shape)

[[[    100     100     300     400 1234500]
  [    100     100     800     900    1000]
  [    100     100    1300    1400    1500]
  [    100     100    1800    1900    2000]]

 [[    200     200     600     800 2469000]
  [    200     200    1600    1800    2000]
  [    200     200    2600    2800    3000]
  [    200     200    3600    3800    4000]]]

Shapes: (4, 5) (2, 1, 1)


## Übung


In [25]:
from numpy import array

x  =  [[ 0.332,  0.49 ,  0.743,  0.688,  0.914,  0.661],
       [ 0.004,  0.285,  0.334,  2.086, -0.164,  0.52 ],
       [ 0.118,  0.482,  0.64 , -1.468,  0.923,  0.088],
       [ 0.995,  0.946, -1.386, -0.75 ,  0.879, -1.105],
       [ 1.072, -0.628, -0.482,  0.838, -0.517, -0.094],
       [-0.125,  0.342,  0.858, -0.626, -2.145,  1.429],
       [ 1.832, -0.471,  0.085,  0.457,  1.449, -0.486]]

y  =  [[ 0.401, -0.468,  0.692, -0.505, -2.672, -0.132],
       [-0.296,  0.54 ,  0.712,  0.496, -0.615, -0.22 ],
       [-0.525, -0.208, -2.41 ,  0.346, -1.93 ,  0.42 ],
       [-0.786,  0.176, -0.652,  0.515,  1.069, -0.457],
       [-0.63 , -1.372, -0.483,  0.608,  1.295, -0.637],
       [-0.286,  1.546, -1.219, -1.779,  0.955, -0.424],
       [-0.435, -1.886, -0.34 , -1.293, -0.646, -1.366]]

ax = array(x)
ay = array(y)

**1) Addieren Sie die beiden Listen `x` und `y` elementweise (also `x[0][0]+y[0][0]`, `x[0][1]+y[0][1]`, usw). Vergleichen Sie die Rechenzeit, wenn Sie Listen verwenden, mit der Zeit, die Sie für die Berechnung mit den Arrays `ax` und `ay` benötigen.**

In [ ]:
%%timeit
# Hier eigenen Code für Listenoperation schreiben ...


In [ ]:
%%timeit
# Hier eigenen Code für Arrayoperation schreiben ...


**2) Geben Sie jede zweite *Zeile* des Arrays `ax` aus. Geben Sie jede zweite *Spalte* des Arrays `ay` aus..**

In [ ]:
# Hier eigenen Code schreiben ...


**3) Kopieren Sie die Werte der beiden Arrays, die *nicht* am Rand liegen, in zwei neue Arrays `xx` und `yy`.**

In [ ]:
# Hier eigenen Code schreiben ...


**4) Überschreiben Sie im Array `xx` die Werte, an deren Position im Array `yy` ein negativer Wert steht, mit dem Quadrat dieses Werts.**

In [ ]:
# Hier eigenen Code schreiben ...


**5) Was passiert im folgenden Programmabschnitt und wie erklärt sich das Ergebnis?**

In [ ]:
y_neu = ay[::2, 1::2]
print(y_neu)
y_neu[:] = 100
print(y_neu)
print(ay)